<?php

$finder = Symfony\CS\Finder\DefaultFinder::create()
    ->files()
    ->name('*.php')
    ->in(__DIR__)
;

return Symfony\CS\Config\Config::create()
    ->level(Symfony\CS\FixerInterface::PSR2_LEVEL)
    ->fixers(array(
        'psr0',
        'psr1',
        'psr2',
        'blankline_after_open_tag',
        'double_arrow_multiline_whitespaces',
        'duplicate_semicolon',
        'empty_return',
        'include',
        'join_function',
        'multiline_array_trailing_comma',
        'namespace_no_leading_whitespace',
        'new_with_braces',
        'no_empty_lines_after_phpdocs',
        'object_operator',
        'operators_spaces',
        'phpdoc_indent',
        'phpdoc_no_empty_return',
        'phpdoc_params',
        'phpdoc_scalar',
        'phpdoc_short_description',
        'phpdoc_trim',
        'phpdoc_type_to_var',
        'phpdoc_types',
        'remove_leading_slash_use',
        'remove_lines_between_uses',
        'return',
        'single_array_no_trailing_comma',
        'single_blank_line_before_namespace',
        'spaces_cast',
        'standardize_not_equal',
        'unused_use',
        'whitespacy_lines',
        'align_double_arrow',
        'concat_with_spaces',
        'long_array_syntax',
        'phpdoc_order',
    ))
    ->finder($finder)
;
